# Taken and adapted from torchaudio.
# Ref: https://github.com/pytorch/audio/blob/main/.github/workflows/ffmpeg.yml
# This job is not directly related to regular CI pipeline.
# It is intended to create FFmpeg binaries that we upload on S3,
# which then will be used during all the build process in CI or local.
#
# This job does not include the uploading part.
# Upload needs to be done manually, and it should be done only once
# per new major release of FFmepg.
name: Build non-GPL FFmpeg from source

on:
  workflow_dispatch:
    inputs:
      tag:
        default: 'latest'
        description: 'ffmpeg version'
        type: string
        required: true
  # schedule:
  #   - cron: '0 0 * * 0'  # on sunday

jobs:
  Get-Version:
    runs-on: ubuntu-latest
    outputs:
      torchcodec_tag: ${{ steps.get-version.outputs.torchcodec_tag }}
      ffmpeg_version: ${{ steps.get-version.outputs.ffmpeg_version }}

    steps:
      - name: Get Version
        id: get-version
        run: |
          tag=${{ inputs.tag }}
          if [ "$tag" = "latest" ]; then
            tag=$(curl --retry 10 -s "https://api.github.com/repos/meta-pytorch/torchcodec/releases/latest" | jq -r .tag_name)
          fi
          if [ -z "${tag}" ] || [ "${tag}" == "null" ]; then
            echo "Failed to get tag"
            exit 1
          fi

          version=$(curl --retry 10 -sSL https://github.com/meta-pytorch/torchcodec/raw/refs/tags/${tag}/src/torchcodec/_core/fetch_and_expose_non_gpl_ffmpeg_libs.cmake | grep -oP 'torchcodec/ffmpeg/\K[0-9-]+')
          if [ -z "${version}" ] || [ "${version}" == "null" ]; then
            echo "Failed to get version"
            exit 1
          fi

          echo "torchcodec_tag=${tag}" >> $GITHUB_OUTPUT
          echo "ffmpeg_version=${version}" >> $GITHUB_OUTPUT
          echo ""
          echo "==== Build Args ===="
          echo "torchcodec: ${tag}"
          echo "ffmpeg: ${version}"

  LGPL-Linux-loongarch64:
    runs-on: ubuntu-latest
    needs: Get-Version
    env:
      torchcodec_tag: ${{ needs.Get-Version.outputs.torchcodec_tag }}
    strategy:
      fail-fast: false
      matrix:
        ffmpeg-version: ["4.4.4", "5.1.4", "6.1.1", "7.0.1", "8.0"]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ffmpeg

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v4

      - name: Build ffmpeg
        run: |
          mkdir -p packaging
          rm -f packaging/build_ffmpeg.sh
          wget -qO packaging/build_ffmpeg.sh https://github.com/meta-pytorch/torchcodec/raw/refs/tags/${torchcodec_tag}/packaging/build_ffmpeg.sh
          sudo chmod +x packaging/build_ffmpeg.sh

          docker run --rm \
            --platform linux/loong64 \
            --volume "$(pwd):/io" \
            --env "FFMPEG_VERSION=${{ matrix.ffmpeg-version }}" \
            --env "FFMPEG_ROOT=/io/ffmpeg" \
            --workdir /io \
            ghcr.io/loong64/manylinuxloongarch64-builder:cpu-loongarch64 \
            /io/packaging/build_ffmpeg.sh

          tar -cf ffmpeg.tar.gz ffmpeg/include ffmpeg/lib
          mv ffmpeg.tar.gz ${{ matrix.ffmpeg-version }}.tar.gz

      - name: Upload FFmpeg Binaries
        uses: actions/upload-artifact@v7
        with:
          name: ffmpeg-${{ matrix.ffmpeg-version }}
          path: "${{ matrix.ffmpeg-version }}.tar.gz"
          if-no-files-found: error
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs:
      - Get-Version
      - LGPL-Linux-loongarch64
    env:
      ffmpeg_version: ${{ needs.Get-Version.outputs.ffmpeg_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ffmpeg
      
      - name: Setup Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: ffmpeg
          pattern: ffmpeg-*
          merge-multiple: true

      - name: Upload artifacts
        run: |
          artifact_dir="${ffmpeg_version}"
          mkdir -p "${artifact_dir}"
          mv ffmpeg "${artifact_dir}/linux_loongarch64"
          git add .
          git commit -m "Update FFmpeg binaries ${ffmpeg_version}"
          git push origin ffmpeg